"""History model

Revision ID: 307947ee6fb3
Revises: e4483aedc097
Create Date: 2019-10-17 09:49:21.413143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '307947ee6fb3'
down_revision = 'e4483aedc097'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_history_timestamp'), 'history', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_history_timestamp'), table_name='history')
    op.drop_column('history', 'timestamp')
    # ### end Alembic commands ###
